python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t flan-t5 -m base --lr 5e-5 --seed 27 -b
python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t flan-t5 -m large --lr 5e-5 --seed 27 -b
python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t t5 -m large --lr 5e-5 --seed 27 -b
python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b
python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t flan-t5 -m base --lr 5e-5 --seed 27 -b
python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t flan-t5 -m large --lr 5e-5 --seed 27 -b
python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t t5 -m large --lr 5e-5 --seed 27 -b
python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus stac --test_corpus stac -s augmented -t flan-t5 -m base --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus stac --test_corpus stac -s augmented -t flan-t5 -m large --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus stac --test_corpus stac -s augmented -t t5 -m large --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus stac --test_corpus stac -s augmented -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus stac --test_corpus stac -s natural -t flan-t5 -m base --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus stac --test_corpus stac -s natural -t flan-t5 -m large --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus stac --test_corpus stac -s natural -t t5 -m large --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus stac --test_corpus stac -s natural -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t flan-t5 -m base --lr 5e-5 --seed 27 -b
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t flan-t5 -m large --lr 5e-5 --seed 27 -b
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t t5 -m large --lr 5e-5 --seed 27 -b
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t flan-t5 -m base --lr 5e-5 --seed 27 -b
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t flan-t5 -m large --lr 5e-5 --seed 27 -b
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t t5 -m large --lr 5e-5 --seed 27 -b
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t flan-t5 -m base --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t flan-t5 -m large --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t t5 -m large --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t flan-t5 -m base --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t flan-t5 -m large --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t t5 -m large --lr 5e-5 --seed 27 -b
python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b