#!/bin/bash
# Auto-generated by gen_slurm_inference.py

mkdir -p slurm/logs

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_focus_t0-3b
#SBATCH --output=slurm/logs/inf_stac_focus_t0-3b_%j.out
#SBATCH --error=slurm/logs/inf_stac_focus_t0-3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t t0-3b  --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t t0-3b  --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_focus_flan-t5_base
#SBATCH --output=slurm/logs/inf_stac_focus_flan-t5_base_%j.out
#SBATCH --error=slurm/logs/inf_stac_focus_flan-t5_base_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t flan-t5 -m base --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t flan-t5 -m base --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_focus_flan-t5_large
#SBATCH --output=slurm/logs/inf_stac_focus_flan-t5_large_%j.out
#SBATCH --error=slurm/logs/inf_stac_focus_flan-t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t flan-t5 -m large --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t flan-t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_focus_flan-t5_xl
#SBATCH --output=slurm/logs/inf_stac_focus_flan-t5_xl_%j.out
#SBATCH --error=slurm/logs/inf_stac_focus_flan-t5_xl_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t flan-t5 -m xl --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t flan-t5 -m xl --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_focus_t5_3b
#SBATCH --output=slurm/logs/inf_stac_focus_t5_3b_%j.out
#SBATCH --error=slurm/logs/inf_stac_focus_t5_3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t t5 -m 3b --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t t5 -m 3b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_focus_t5_large
#SBATCH --output=slurm/logs/inf_stac_focus_t5_large_%j.out
#SBATCH --error=slurm/logs/inf_stac_focus_t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t t5 -m large --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_focus_t5gemma2_270m
#SBATCH --output=slurm/logs/inf_stac_focus_t5gemma2_270m_%j.out
#SBATCH --error=slurm/logs/inf_stac_focus_t5gemma2_270m_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_focus_t5gemma2_1b
#SBATCH --output=slurm/logs/inf_stac_focus_t5gemma2_1b_%j.out
#SBATCH --error=slurm/logs/inf_stac_focus_t5gemma2_1b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_focus_t5gemma2_4b
#SBATCH --output=slurm/logs/inf_stac_focus_t5gemma2_4b_%j.out
#SBATCH --error=slurm/logs/inf_stac_focus_t5gemma2_4b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_2g.20gb --cpus-per-task=4 --mem=16G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s focus -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural2_t0-3b
#SBATCH --output=slurm/logs/inf_stac_natural2_t0-3b_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural2_t0-3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t t0-3b  --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t t0-3b  --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural2_flan-t5_base
#SBATCH --output=slurm/logs/inf_stac_natural2_flan-t5_base_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural2_flan-t5_base_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t flan-t5 -m base --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t flan-t5 -m base --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural2_flan-t5_large
#SBATCH --output=slurm/logs/inf_stac_natural2_flan-t5_large_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural2_flan-t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t flan-t5 -m large --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t flan-t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural2_flan-t5_xl
#SBATCH --output=slurm/logs/inf_stac_natural2_flan-t5_xl_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural2_flan-t5_xl_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t flan-t5 -m xl --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t flan-t5 -m xl --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural2_t5_3b
#SBATCH --output=slurm/logs/inf_stac_natural2_t5_3b_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural2_t5_3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t t5 -m 3b --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t t5 -m 3b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural2_t5_large
#SBATCH --output=slurm/logs/inf_stac_natural2_t5_large_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural2_t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t t5 -m large --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural2_t5gemma2_270m
#SBATCH --output=slurm/logs/inf_stac_natural2_t5gemma2_270m_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural2_t5gemma2_270m_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural2_t5gemma2_1b
#SBATCH --output=slurm/logs/inf_stac_natural2_t5gemma2_1b_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural2_t5gemma2_1b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural2_t5gemma2_4b
#SBATCH --output=slurm/logs/inf_stac_natural2_t5gemma2_4b_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural2_t5gemma2_4b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_2g.20gb --cpus-per-task=4 --mem=16G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus stac --test_corpus stac -s natural2 -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_augmented_t0-3b
#SBATCH --output=slurm/logs/inf_stac_augmented_t0-3b_%j.out
#SBATCH --error=slurm/logs/inf_stac_augmented_t0-3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s augmented -t t0-3b  --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s augmented -t t0-3b  --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_augmented_flan-t5_base
#SBATCH --output=slurm/logs/inf_stac_augmented_flan-t5_base_%j.out
#SBATCH --error=slurm/logs/inf_stac_augmented_flan-t5_base_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s augmented -t flan-t5 -m base --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s augmented -t flan-t5 -m base --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_augmented_flan-t5_large
#SBATCH --output=slurm/logs/inf_stac_augmented_flan-t5_large_%j.out
#SBATCH --error=slurm/logs/inf_stac_augmented_flan-t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s augmented -t flan-t5 -m large --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s augmented -t flan-t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_augmented_flan-t5_xl
#SBATCH --output=slurm/logs/inf_stac_augmented_flan-t5_xl_%j.out
#SBATCH --error=slurm/logs/inf_stac_augmented_flan-t5_xl_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s augmented -t flan-t5 -m xl --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s augmented -t flan-t5 -m xl --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_augmented_t5_3b
#SBATCH --output=slurm/logs/inf_stac_augmented_t5_3b_%j.out
#SBATCH --error=slurm/logs/inf_stac_augmented_t5_3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s augmented -t t5 -m 3b --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s augmented -t t5 -m 3b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_augmented_t5_large
#SBATCH --output=slurm/logs/inf_stac_augmented_t5_large_%j.out
#SBATCH --error=slurm/logs/inf_stac_augmented_t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s augmented -t t5 -m large --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s augmented -t t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_augmented_t5gemma2_270m
#SBATCH --output=slurm/logs/inf_stac_augmented_t5gemma2_270m_%j.out
#SBATCH --error=slurm/logs/inf_stac_augmented_t5gemma2_270m_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s augmented -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s augmented -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_augmented_t5gemma2_1b
#SBATCH --output=slurm/logs/inf_stac_augmented_t5gemma2_1b_%j.out
#SBATCH --error=slurm/logs/inf_stac_augmented_t5gemma2_1b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s augmented -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s augmented -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_augmented_t5gemma2_4b
#SBATCH --output=slurm/logs/inf_stac_augmented_t5gemma2_4b_%j.out
#SBATCH --error=slurm/logs/inf_stac_augmented_t5gemma2_4b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_2g.20gb --cpus-per-task=4 --mem=16G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s augmented -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s augmented -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural_t0-3b
#SBATCH --output=slurm/logs/inf_stac_natural_t0-3b_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural_t0-3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s natural -t t0-3b  --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s natural -t t0-3b  --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural_flan-t5_base
#SBATCH --output=slurm/logs/inf_stac_natural_flan-t5_base_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural_flan-t5_base_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s natural -t flan-t5 -m base --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s natural -t flan-t5 -m base --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural_flan-t5_large
#SBATCH --output=slurm/logs/inf_stac_natural_flan-t5_large_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural_flan-t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s natural -t flan-t5 -m large --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s natural -t flan-t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural_flan-t5_xl
#SBATCH --output=slurm/logs/inf_stac_natural_flan-t5_xl_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural_flan-t5_xl_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s natural -t flan-t5 -m xl --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s natural -t flan-t5 -m xl --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural_t5_3b
#SBATCH --output=slurm/logs/inf_stac_natural_t5_3b_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural_t5_3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s natural -t t5 -m 3b --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s natural -t t5 -m 3b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural_t5_large
#SBATCH --output=slurm/logs/inf_stac_natural_t5_large_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural_t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s natural -t t5 -m large --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s natural -t t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural_t5gemma2_270m
#SBATCH --output=slurm/logs/inf_stac_natural_t5gemma2_270m_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural_t5gemma2_270m_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s natural -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s natural -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural_t5gemma2_1b
#SBATCH --output=slurm/logs/inf_stac_natural_t5gemma2_1b_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural_t5gemma2_1b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s natural -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s natural -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_stac_natural_t5gemma2_4b
#SBATCH --output=slurm/logs/inf_stac_natural_t5gemma2_4b_%j.out
#SBATCH --error=slurm/logs/inf_stac_natural_t5gemma2_4b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_2g.20gb --cpus-per-task=4 --mem=16G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus stac --test_corpus stac -s natural -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus stac --test_corpus stac -s natural -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_focus_t0-3b
#SBATCH --output=slurm/logs/inf_molweni_focus_t0-3b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_focus_t0-3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t t0-3b  --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t t0-3b  --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_focus_flan-t5_base
#SBATCH --output=slurm/logs/inf_molweni_focus_flan-t5_base_%j.out
#SBATCH --error=slurm/logs/inf_molweni_focus_flan-t5_base_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t flan-t5 -m base --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t flan-t5 -m base --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_focus_flan-t5_large
#SBATCH --output=slurm/logs/inf_molweni_focus_flan-t5_large_%j.out
#SBATCH --error=slurm/logs/inf_molweni_focus_flan-t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t flan-t5 -m large --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t flan-t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_focus_flan-t5_xl
#SBATCH --output=slurm/logs/inf_molweni_focus_flan-t5_xl_%j.out
#SBATCH --error=slurm/logs/inf_molweni_focus_flan-t5_xl_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t flan-t5 -m xl --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t flan-t5 -m xl --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_focus_t5_3b
#SBATCH --output=slurm/logs/inf_molweni_focus_t5_3b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_focus_t5_3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t t5 -m 3b --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t t5 -m 3b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_focus_t5_large
#SBATCH --output=slurm/logs/inf_molweni_focus_t5_large_%j.out
#SBATCH --error=slurm/logs/inf_molweni_focus_t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t t5 -m large --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_focus_t5gemma2_270m
#SBATCH --output=slurm/logs/inf_molweni_focus_t5gemma2_270m_%j.out
#SBATCH --error=slurm/logs/inf_molweni_focus_t5gemma2_270m_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_focus_t5gemma2_1b
#SBATCH --output=slurm/logs/inf_molweni_focus_t5gemma2_1b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_focus_t5gemma2_1b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_focus_t5gemma2_4b
#SBATCH --output=slurm/logs/inf_molweni_focus_t5gemma2_4b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_focus_t5gemma2_4b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_2g.20gb --cpus-per-task=4 --mem=16G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s focus -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural2_t0-3b
#SBATCH --output=slurm/logs/inf_molweni_natural2_t0-3b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural2_t0-3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t t0-3b  --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t t0-3b  --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural2_flan-t5_base
#SBATCH --output=slurm/logs/inf_molweni_natural2_flan-t5_base_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural2_flan-t5_base_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t flan-t5 -m base --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t flan-t5 -m base --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural2_flan-t5_large
#SBATCH --output=slurm/logs/inf_molweni_natural2_flan-t5_large_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural2_flan-t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t flan-t5 -m large --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t flan-t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural2_flan-t5_xl
#SBATCH --output=slurm/logs/inf_molweni_natural2_flan-t5_xl_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural2_flan-t5_xl_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t flan-t5 -m xl --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t flan-t5 -m xl --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural2_t5_3b
#SBATCH --output=slurm/logs/inf_molweni_natural2_t5_3b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural2_t5_3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t t5 -m 3b --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t t5 -m 3b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural2_t5_large
#SBATCH --output=slurm/logs/inf_molweni_natural2_t5_large_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural2_t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t t5 -m large --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural2_t5gemma2_270m
#SBATCH --output=slurm/logs/inf_molweni_natural2_t5gemma2_270m_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural2_t5gemma2_270m_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural2_t5gemma2_1b
#SBATCH --output=slurm/logs/inf_molweni_natural2_t5gemma2_1b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural2_t5gemma2_1b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural2_t5gemma2_4b
#SBATCH --output=slurm/logs/inf_molweni_natural2_t5gemma2_4b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural2_t5gemma2_4b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_2g.20gb --cpus-per-task=4 --mem=16G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b"
python3 transition_predict.py --train_corpus molweni --test_corpus molweni -s natural2 -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_augmented_t0-3b
#SBATCH --output=slurm/logs/inf_molweni_augmented_t0-3b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_augmented_t0-3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t t0-3b  --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t t0-3b  --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_augmented_flan-t5_base
#SBATCH --output=slurm/logs/inf_molweni_augmented_flan-t5_base_%j.out
#SBATCH --error=slurm/logs/inf_molweni_augmented_flan-t5_base_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t flan-t5 -m base --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t flan-t5 -m base --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_augmented_flan-t5_large
#SBATCH --output=slurm/logs/inf_molweni_augmented_flan-t5_large_%j.out
#SBATCH --error=slurm/logs/inf_molweni_augmented_flan-t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t flan-t5 -m large --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t flan-t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_augmented_flan-t5_xl
#SBATCH --output=slurm/logs/inf_molweni_augmented_flan-t5_xl_%j.out
#SBATCH --error=slurm/logs/inf_molweni_augmented_flan-t5_xl_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t flan-t5 -m xl --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t flan-t5 -m xl --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_augmented_t5_3b
#SBATCH --output=slurm/logs/inf_molweni_augmented_t5_3b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_augmented_t5_3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t t5 -m 3b --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t t5 -m 3b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_augmented_t5_large
#SBATCH --output=slurm/logs/inf_molweni_augmented_t5_large_%j.out
#SBATCH --error=slurm/logs/inf_molweni_augmented_t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t t5 -m large --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_augmented_t5gemma2_270m
#SBATCH --output=slurm/logs/inf_molweni_augmented_t5gemma2_270m_%j.out
#SBATCH --error=slurm/logs/inf_molweni_augmented_t5gemma2_270m_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_augmented_t5gemma2_1b
#SBATCH --output=slurm/logs/inf_molweni_augmented_t5gemma2_1b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_augmented_t5gemma2_1b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_augmented_t5gemma2_4b
#SBATCH --output=slurm/logs/inf_molweni_augmented_t5gemma2_4b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_augmented_t5gemma2_4b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_2g.20gb --cpus-per-task=4 --mem=16G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s augmented -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural_t0-3b
#SBATCH --output=slurm/logs/inf_molweni_natural_t0-3b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural_t0-3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t t0-3b  --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t t0-3b  --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural_flan-t5_base
#SBATCH --output=slurm/logs/inf_molweni_natural_flan-t5_base_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural_flan-t5_base_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t flan-t5 -m base --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t flan-t5 -m base --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural_flan-t5_large
#SBATCH --output=slurm/logs/inf_molweni_natural_flan-t5_large_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural_flan-t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t flan-t5 -m large --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t flan-t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural_flan-t5_xl
#SBATCH --output=slurm/logs/inf_molweni_natural_flan-t5_xl_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural_flan-t5_xl_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t flan-t5 -m xl --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t flan-t5 -m xl --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural_t5_3b
#SBATCH --output=slurm/logs/inf_molweni_natural_t5_3b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural_t5_3b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t t5 -m 3b --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t t5 -m 3b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural_t5_large
#SBATCH --output=slurm/logs/inf_molweni_natural_t5_large_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural_t5_large_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t t5 -m large --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t t5 -m large --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural_t5gemma2_270m
#SBATCH --output=slurm/logs/inf_molweni_natural_t5gemma2_270m_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural_t5gemma2_270m_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t t5gemma2 -m 270m --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural_t5gemma2_1b
#SBATCH --output=slurm/logs/inf_molweni_natural_t5gemma2_1b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural_t5gemma2_1b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_1g.10gb --cpus-per-task=4 --mem=8G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t t5gemma2 -m 1b --lr 5e-5 --seed 27 -b
EOT

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=inf_molweni_natural_t5gemma2_4b
#SBATCH --output=slurm/logs/inf_molweni_natural_t5gemma2_4b_%j.out
#SBATCH --error=slurm/logs/inf_molweni_natural_t5gemma2_4b_%j.err
#SBATCH --gpus=nvidia_h100_80gb_hbm3_2g.20gb --cpus-per-task=4 --mem=16G --time=02:00:00

source slurm/init_hpc.sh

echo "Running: python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b"
python3 train.py --train_corpus molweni --test_corpus molweni -s natural -t t5gemma2 -m 4b --lr 5e-5 --seed 27 -b
EOT
