import argparse
import os
import shlex

def get_job_name(tokens):
    """
    Extracts relevant parts from the command tokens to form a job name.
    Example job name: inf_stac_focus_t0-3b_3b
    """
    parts = ["inf"]
    
    # Extract corpus
    if '--train_corpus' in tokens:
        parts.append(tokens[tokens.index('--train_corpus') + 1])
    elif '--test_corpus' in tokens:
        parts.append(tokens[tokens.index('--test_corpus') + 1])
        
    # Extract structure type (-s)
    if '-s' in tokens:
        parts.append(tokens[tokens.index('-s') + 1])
        
    # Extract model family (-t)
    if '-t' in tokens:
        parts.append(tokens[tokens.index('-t') + 1])
        
    # Extract model size (-m)
    if '-m' in tokens:
        parts.append(tokens[tokens.index('-m') + 1])
        
    return "_".join(parts)


def get_resources(tokens):
    """
    Determines Slurm resources based on the model size and type.
    """
    model_size = None
    if '-m' in tokens:
        try:
            model_size = tokens[tokens.index('-m') + 1]
        except IndexError:
            pass
            
    # Default to 1g.10gb for small models (3B, 1B, base, large)
    # 3B params in bf16 ~ 6GB VRAM
    # 1B params in bf16 ~ 2GB VRAM
    gres = "--gpus=nvidia_h100_80gb_hbm3_1g.10gb:1"
    mem = "8G" 
    
    # For larger models (4B+ or if we want to be safe with 4B)
    # 4B params in bf16 ~ 8GB VRAM (tight in 10GB with context overhead)
    if model_size in ['4b', '11b', 'xxl']:
        gres = "--gpus=nvidia_h100_80gb_hbm3_2g.20gb:1"  # Use 20GB slice for 4B+ just to be safe
        mem = "16G"
        
    return f"{gres} --cpus-per-task=4 --mem={mem} --time=04:00:00"


def main():
    parser = argparse.ArgumentParser(description="Generate Slurm submission script for inference jobs.")
    parser.add_argument("--input_script", type=str, default="run_predict.sh", help="Path to the shell script containing python commands.")
    parser.add_argument("--output_script", type=str, default="submit_predict_jobs.sh", help="Output submission script.")
    args = parser.parse_args()

    if not os.path.exists(args.input_script):
        # Try looking in parent directory if not found in current (e.g., if running from slurm/)
        if os.path.exists(os.path.join("..", args.input_script)):
            args.input_script = os.path.join("..", args.input_script)
        else:
            print(f"Error: Input script '{args.input_script}' not found.")
            return

    print(f"Reading commands from {args.input_script}...")
    
    with open(args.input_script, 'r') as f:
        lines = f.readlines()

    submission_commands = []
    
    # Header for the main submission script
    submission_commands.append("#!/bin/bash")
    submission_commands.append(f"# Auto-generated by {os.path.basename(__file__)}")
    submission_commands.append("")
    submission_commands.append("mkdir -p slurm/logs")
    submission_commands.append("")

    job_counter = 0

    for line in lines:
        line = line.strip()
        
        # Skip empty lines and comments
        if not line or line.startswith('#'):
            continue
            
        # We only care about python commands
        if 'python3' in line:
            tokens = shlex.split(line)
            job_name = get_job_name(tokens)
            resources = get_resources(tokens)
            
            # Construct the sbatch heredoc
            # We use a heredoc to feed the job script directly to sbatch
            sbatch_cmd = f"""sbatch <<EOT
#!/bin/bash
#SBATCH --job-name={job_name}
#SBATCH --output=slurm/logs/inference/{job_name}_%j.out
#SBATCH --error=slurm/logs/inference/{job_name}_%j.err
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=wut2@unbc.ca
#SBATCH {resources}

cd $HOME/scratch/Seq2Seq-DDP
source slurm/init_hpc.sh

echo "Running: {line}"
{line}
EOT
"""
            submission_commands.append(sbatch_cmd)
            job_counter += 1

    print(f"Generated {job_counter} job submissions.")

    with open(args.output_script, 'w') as f:
        f.write("\n".join(submission_commands))

    os.chmod(args.output_script, 0o755)
    print(f"Submission script written to: {args.output_script}")
    print("Run it with: ./submit_predict_jobs.sh")

if __name__ == "__main__":
    main()
